### ISSUE TITLE
Client name doesn't match

### ISSUE THREAD

**Issue by hucknz** [Schaka/rarrnomore#1]
Hey, thanks for building this! Like you I've had a lot of problems with TL and rar files recently so this is awesome. 

I'm getting what I think is an error in the container logs stating "Client name doesn't match". Any pointers as to what that error is being caused by?

**Comment by hucknz** [comment]
Figured it out, there's a typo in the application.yml example:

https://github.com/Schaka/rarrnomore/blob/d84accd7b99f7815febd42776486d2974accc19c/src/main/resources/application.yml#L13

**Comment by Schaka** [comment]
Thanks for the report, I'll get that sorted. Must've slipped i when I cleaned up the files.
Embarrassingly, my client in Sonarr is actually spelled with 1 't'. I adjust the template though.
![image](https://github.com/Schaka/rarrnomore/assets/2223171/a457829b-6d24-4fef-8568-1aa2a8ae43fa)

**Comment by hucknz** [comment]
Haha, we all have those embarrassing typos! Thanks for sorting that. 

I may have another potential bug (I'll raise in a separate issue) but I'll keep an eye out to see if it was just a bad day yesterday or if it continues to occur over the next few days.
