### ISSUE TITLE
Option to disable torrent resuming

### ISSUE THREAD

**Issue by TheFirstMonster** [Schaka/rarrnomore#6]
It would be good to have an option in the config that disables resuming the download of torrents after checking for rar files.

**Comment by Schaka** [comment]
Can you explain a little more? Personally, I feel like it defeats the purpose.
You end up with a bunch of paused torrents and your *arr apps will get stuck.

**Comment by TheFirstMonster** [comment]
> Can you explain a little more? Personally, I feel like it defeats the purpose. You end up with a bunch of paused torrents and your *arr apps will get stuck.

Me personally, like to have a quick look over what torrents Radarr/Sonarr/etc tries to download and then sign them off. Because for example some mislabeled torrent snuck through my filters and got grabbed, which is something that can happen but something I don't want. Which is especially important with private trackers where ratio is a matter or with limited resources on the download machine. Without starting any torrents rarrnomore is still of great help by saving me one step of removing rared torrents, so I'm left with more potentially good ones. I understand that this is something that in an environment with a lot of downloads by many different users is not applicable, but I don't see a reason to not include the option.

**Comment by Schaka** [comment]
That's good enough of a reason for me. I'll see if I can get it added by next week.

**Comment by Schaka** [comment]
Fixed in https://github.com/Schaka/rarrnomore/releases/tag/v0.9.7c
