### ISSUE TITLE
CPU flag issue for Intel(R) Xeon(R) CPU E31230

### ISSUE THREAD

**Issue by t-abraham** [Schaka/rarrnomore#8]
`Please rebuild the executable with an appropriate setting of the -march option. The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].`

Can you please assist me with it? I am using the docker image. Thanks

**Comment by Schaka** [comment]
You'll have to use the non-native image. Your CPU is too old (nearly 15 years) and lacks AVX2 instructions.

You can also copy the build section from [janitorr](https://github.com/Schaka/janitorr/blob/main/build.gradle.kts#L185), which adds compatibility mode. However, that requires upgrading dependencies to Spring Boot 3.4 and probably adjusting the build pipeline. 

That's not effort I'm willing to put into rarrnomore anymore, as I stopped using it.

**Comment by ghostkernel-core** [comment]
the latest tag also has the same issue

**Comment by Schaka** [comment]
You should be able to use `:v1.1.2` explicitly.

**Comment by ghostkernel-core** [comment]
okey thanks a lot. it works. By the way you said you are not using this anymore, then what are you using to tackle the rar captures?

**Comment by Schaka** [comment]
I'm using trackers and quality profiles that don't result in shitty scene release grabs, basically.

**Comment by ghostkernel-core** [comment]
makes more sense and more reasons to leave a certain tracker :)
